"""user_id company_id

Revision ID: b36898a67d5a
Revises: 
Create Date: 2025-08-07 22:37:50.113892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b36898a67d5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qm_updates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fk_qm_updates_company_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'company_info', ['fk_qm_updates_company_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qm_updates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fk_qm_updates_company_id')
        batch_op.drop_column('sender_id')

    # ### end Alembic commands ###
